pipeline_type: "streamdiffusionv2"

pipeline:
  generator_path: "StreamDiffusionV2/wan_causal_dmd_v2v/model.pt"
  text_encoder_path: "WanVideo_comfy/umt5-xxl-enc-fp8_e4m3fn.safetensors"
  tokenizer_path: "Wan2.1-T2V-1.3B/google/umt5-xxl"

controlnet:
  repo_id: "TheDenk/wan2.1-t2v-1.3b-controlnet-depth-v1"
  filename: "diffusion_pytorch_model.safetensors"
  local_subpath: "LongLive-1.3B/controlnets/wan2.1-t2v-1.3b-controlnet-depth-v1.safetensors"

preprocessor:
  type: "depth"
  output_video_path: "controlnet_test/control_frames_streamdiffusionv2_depth.mp4"

conditioning_scale: 10.5
compression_ratio: 4

chunk_size: 4
start_chunk_size: 5

# Optional: denoising steps (defaults to [750, 250] if not specified)
# denoising_step_list: [750, 250]
denoising_step_list: [1000, 999]

prompt: "a bear is walking on the grass"

input_video: "pipelines/streamdiffusionv2/assets/original.mp4"

height: 480
width: 832
